TECH_SKILLS = [

    # Languages
    "c",
    "c++",
    "c#",
    "java",
    "python",
    "javascript",
    "typescript",
    "php",
    "go",
    "rust",

    # .NET
    ".net",
    ".net core",
    "asp.net",
    "asp.net core",
    "entity framework",
    "entity framework core",
    "linq",
    "mvc",
    "web api",

    # Frontend
    "react",
    "redux",
    "angular",
    "vue",
    "html",
    "css",
    "bootstrap",
    "tailwind",

    # Database
    "sql",
    "sql server",
    "mysql",
    "postgresql",
    "mongodb",
    "redis",

    # AI/ML
    "machine learning",
    "deep learning",
    "nlp",
    "fastapi",
    "qdrant",
    "langchain",
    "rag",
    "gpt",
    "bert",
    "sbert",

    # DevOps
    "docker",
    "kubernetes",
    "azure",
    "aws",
    "git",
    "github",
    "ci/cd",

    # Backend
    "jwt",
    "oauth",
    "rest api",
    "graphql",
    "microservices",
    "swagger",
    "dependency injection",

    # Soft Skills (ACTUAL SKILLS)
    "communication",
    "leadership",
    "teamwork",
    "team management",
    "project management",
    "problem solving",
    "analytical thinking",
    "critical thinking",
    "negotiation",
    "interpersonal skills",
    "customer service",
    "presentation",
    "public speaking",
    "adaptability",
    "resilience",
    "creativity",
    "innovation",
    "conflict resolution",
    "delegation",
    "mentoring",
    "training",
    "coaching",

    # Business Skills (ACTUAL SKILLS)
    "sales",
    "business development",
    "marketing",
    "finance",
    "accounting",
    "contract negotiation",
    "stakeholder management",
    "vendor management",
    "supply chain management",
    "procurement",
    "budget management",
    "strategic planning",
    "market analysis",
    "competitive analysis",
    "risk management",
    "compliance",
    "quality management",
    "process improvement",
    "lean management",
    "six sigma",
    "operations management",
    "human resource management",
    "recruitment",
    "employee relations",

    # Office/Productivity Tools (ACTUAL SKILLS)
    "excel",
    "word",
    "powerpoint",
    "access",
    "outlook",
    "salesforce",
    "sap",
    "erp",
    "crm",
    "asana",
    "jira",
    "confluence",
    "slack",
    "teams",
    "zoom",
    "tableau",
    "power bi",
    "looker",
    "quickbooks",

    # Industry Knowledge (ACTUAL SKILLS - when used as expertise)
    "construction management",
    "manufacturing",
    "healthcare management",
    "retail management",
    "hospitality management",
    "logistics management",
    "agricultural management",
    "government relations",
    "telecommunications",
    "transportation management",
    "energy management",
    "elevator industry",
    "building materials knowledge",
    "electrical systems",
    "electrical engineering",

]
